### ISSUE TITLE
How to setConfig?

### ISSUE THREAD

**Issue by chrispaterson** [modernweb-dev/storybook-prebuilt#132]
It seems like `addons` are not part of the opinionated set?  I have a component which takes a text input and my panels fly in and out when I type.  I'd like to be able to disable storybook shortcuts, like this page describes: https://storybook.js.org/docs/react/configure/features-and-behavior but can't figure out how to do that with this package?

**Comment by Westbrook** [comment]
I can't say that I've tried _everyone_ of the options in the config, but I do it by having a `.storybook/manager.js` file and including code as seen in the URL you've included. Usage is probably a good add to the demos in https://github.com/modernweb-dev/web/tree/master/packages/dev-server-storybook as well as the demos in this repo (though they're more for release testing than for learning to consume the library at this point) so that it can be seen in action.

Here's an example in the wild: https://github.com/adobe/spectrum-web-components/blob/main/.storybook/manager.js

**Comment by chrispaterson** [comment]
Oh!  So addons is there!  Great, thanks!
